project:
  type: book

book:
  title: 'iHuman Lab Manual'
  author: 'Hemanth Manjunatha'
  date: today
  page-navigation: true
  sidebar:
    logo: images/logo.png
    search: true
  chapters:
    - index.qmd
    - introduction.qmd
    - part: rights_and_responsibilities/rights_and_responsibilities.qmd
      chapters:
        - rights_and_responsibilities/project_roles.qmd
        - rights_and_responsibilities/code_of_conduct.qmd
    - getting_started_in_the_lab.qmd
      # chapters:
      # - getting_started/starting_a_new_project.qmd
    - part: lab_practices/lab_practices_and_policies.qmd
      chapters:
        - lab_practices/scientific_integrity.qmd
        - lab_practices/making_mistakes.qmd
        - lab_practices/communication.qmd
        - lab_practices/lab_meetings.qmd
        - lab_practices/travel_policy.qmd
        - lab_practices/authorship_guidlines.qmd
        - lab_practices/deadlines.qmd
        - lab_practices/lab_attendance.qmd
        - lab_practices/lab_traditions.qmd
    - lab_resources.qmd
    # - lab_members_and_alumni.qmd
    - checklist_and_signature.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, custom.scss]
    highlight-style: dracula
  pdf:
    documentclass: scrreprt
