# Lab resources {.unnumbered}

As with most academic research labs, we (sadly!) must conduct our research within a limited research budget. In practice, the important thing is to communicate with Hemanth before you spend (or commit to spending) lab funds.
Generally, the lab's financial policy is the following: we will do whatever is possible to ensure you have the equipment and resources you need to do your best work. If you can adequately justify an expense and sufficient funds are available, then we will spend what it takes to get the job done. If you cannot justify an expense, or if the lab does not have sufficient funds, then we will need to get creative by figuring out how to get the job done anyway on a seemingly too-small budget. Usually, we'll find ourselves somewhere in the middle of this continuum, which will help us stretch our limited budget as much as possible while not making ourselves crazy or losing too much productivity in the process.
Some of our projects are intended to be self-funded and/or to support other projects (e.g., StockProphet). Any use of project-generated funds should be discussed with Hemanth.

## Computers
All lab members need a computer to get their work done. We generally prefer to use Linux machines, as this maximizes compatibility across lab members. Depending on your expected role in the lab and the specifics of your project, the lab may provide a computer to you, or you may be expected to use your personal computer to complete your work. Any equipment purchased by the lab, including personal computers, is the official property of the iHuman Lab and should be treated as such. All equipment must be returned to the lab when your association with the lab is complete. In addition to personal computers, we also maintain a lab account at Oklahoma State University's Supercomputing Cluster.

## Other research equipment
Many research projects require specialized research equipment (e.g. for neuroimaging using EEG, ECoG, etc.). Some of the necessary research equipment is owned by the iHuman Lab, and other equipment is shared with other labs affiliated with PBS or DHMC. All equipment should be treated with care and respect. Any malfunctions should be reported immediately.

## Repository of shared lab papers and books
Our lab maintains a Dropbox repository of PDFs for internal use by lab members and affiliates. Contact Hemanth for a link (not to be shared publicly).