# Communication {.unnumbered}

In my experience, one of the strongest predictors of whether people will do well in the lab is their ability to communicate effectively, both with me and with others. Often there are two key barriers:

- Sometimes people worry that if they communicate questions or struggles, they will be seen as somehow inferior for not knowing something. In fact, that's rarely the case, and the opposite is a much bigger concern! People who don't communicate often get hung up on specific issues (that may be very challenging, and could really use outside perspective/discussion). Ultimately this leads to someone being much less productive than the person who's willing to ask questions. On the other hand, I've never once worried about somebody not knowing something - everyone in the lab is around because we believe in their talents. So the right decision is most often to just speak up! Try to overcome your [imposter syndrome](https://www.chronicle.com/article/how-to-overcome-impostor-syndrome/){target="_blank_"}, and focus on working with your colleagues (me, other lab members) to find a solution to the problem.
- A second issue is that we're often afraid of "bothering" more senior people (undergrads worry about bothering grad students, grad students worry about bothering postdocs, everybody worries about bothering the PI, etc). I feel the same way about potentially bothering my own mentors and supervisors! Fight that instinct. Bottom line - I much prefer that people in the lab speak up, and I have no problem telling people if they are in fact bothering me (so far, this has never happened).
If these are sources of anxiety, I totally get it. However, if it's possible to overcome them, your time in lab will end up being much easier, and likely your productivity will increase quite a bit!

If these are sources of anxiety, I totally get it. However, if it's possible to overcome them, your time in lab will end up being much easier, and likely your productivity will increase quite a bit!

In general, I *do not* expect you to respond to things on weekends or after hours. I do sometimes send emails or `Slack` messages during those times - that's just because I get to stuff when I get to it. Don't feel pressured to respond until you're back to work yourself! I only expect you to be responsive after hours during specific critical time periods (e.g., right before a submission deadline or leading up to a conference presentation). We should be able to anticipate those cases and agree upon a strategy in advance. If there's anything distressing about off-hours messages, just let me know, and I'll try not to bother you during those times.