# Lab practices and policies {.unnumbered}

Our lab’s practices and policies are intended to provide a framework for maximizing efficiency. Achieving our peak efficiency as a lab means we are being as scientifically productive as possible, in terms of knowledge discovery (learning new stuff) and dissemination (papers, talks, conference presentations, publicly released datasets, software, etc.). It also means that our fellow lab members are achieving their training and career objectives. To achieve peak efficiency, we follow these principles:

* **`Collaboration`**: Our lab benefits greatly by being an intellectually diverse team. We bring in expertise from many disciplines, e.g., Computer Science, Neuroscience, Biomedical Engineering. No one in the lab (including myself) has the background necessary to tackle all the problems we're trying to solve. Therefore, the only way we can be successful is by fostering an openly collaborative and communicative environment. Ultimately, our group strongly selects for team members who are comfortable admitting what they don't know and learning new material as they go (both through independent research and discussion with colleagues).

* **`Patience`**: As mentioned above - if we already knew the answer, we would not be studying the question. Similarly, if the work was easy, usually someone else would've done it already. From that standpoint, we fundamentally expect our experiments and approaches to fail more often than they succeed. So while we're always shooting for success, it's important to have thick skin and not get overly frustrated when things aren't working out. Just keep working diligently, keep thinking through the problem, and keep discussing it with your colleagues. It's also important to continually make honest evaluations on whether a problem is worth pushing on further, or when it's worth cutting our losses and moving on.

* **`Accept the process`**: Don't hide or be afraid of contradictory results, mistakes, bugs, etc. We're going to make mistakes, and we'll find plenty of results that challenge our hypotheses, or that we don't initially know how to explain. So even if something is intimidating or embarassing, the only way forward is to face it head-on and openly, figure out solutions, and move on.

* **`Caution`**: Science is about being extremely careful and thorough. Double and triple check every result. Be extremely skeptical about results, and think through every way they could be wrong before concluding that they're correct. Ask others to look at your results and think of ways they might be wrong. If we apply extremely high standards internally, then our work will easily pass external review.

* **`Attention to detail`**: Our studies often involve complex systems and processes, with many points of failure that could doom an entire experiment or analysis. So careful attention to detail and quality control are crucial for making sure things keep moving forward.

* **`Communication`**: Technical skills are important, but equally (if not more important) are communication skills. No one in our lab works in isolation (see first item above!) - at a minimum, you communicate frequently with your PI (me), and likely work closely with other lab members and collaborators. So without sustained effort from everyone to communicate, it's easy for things to go off track, for there to be misunderstandings or duplicated efforts, etc.

* **`Feedback`**: We want everyone in the lab to be comfortable giving and receiving direct, constructive criticism and feedback. It's extremely challenging to open up your thoughts and ideas to criticism, for fear that people will judge you personally. But if everyone is comfortable giving and receiving feedback that is never personal, it opens us up to different perspectives. Often this will reveal flaws in ideas that are hard to see when you're too close to them, and new solutions. Similarly, it's easy to get too attached to ideas because they're your own - we all have an instinct to go prove our ideas and show how clever we are. In our lab environment, that's not the goal! There's no "extra credit" for doing things on your own. It's much more important to find ways to solve the problem and discover truth, and the folks around you are wonderful resources to make that happen.

* **`Positivity`**: Everyone on our team is working on a challenging set of problems. Being positive and supportive makes the endeavor more enjoyable for everyone. If you run into issues where it's difficult to be positive and supportive with your colleagues, take a break and come talk to me, we'll work something out.

* **`Balance`**: Don't try to work 24/7, if for no other reason than you'll just find yourself staring at a screen without doing anything productive. Work smarter - I find it helpful to create focused blocks where I eliminate distractions. However you do it, make sure you take breaks to refresh your mind, and have a life outside of lab. There are obvious benefits for your mental health, but you'll also find yourself refreshed and productive when you do get back to work.

* **`Resource allocation`**: Our lab resources (e.g. equipment, time, money, attention) are finite. We want to foster an environment where lab resources are used as efficiently as possible to achieve our collective goals. We also want to foster sustainable use of resources by regularly pursuing research funding opportunities.


Your job as a contributing lab member is to help us to achieve our collective peak efficiency (as a lab) while also maximizing your own training and career potential.