# Overview {.unnumbered}

## Big Picture

- Do work that you are proud of. Do work that others will care about.
- Double-check your work. Being a little obsessive is essential to good science.
- Be supportive of your labmates. We are a team.
- Work independently when you can, ask for help when you need it.
- Share your knowledge. Mentorship can take many forms.
- Respect each others' strengths, weaknesses, differences, and beliefs.
- Science is a marathon, not a sprint. Take personal time/ vacation when you need it and cultivate a
- life outside of the lab. Respect that other lab members also have a life outside of lab.
- Communicate openly and respectfully with other members of the lab.
- If you have an issue with another lab member that cannot be solved by talking with them about it, please talk with Hemanth.
- Academia may feel different from other types of jobs, but it is still a job. You should treat coming into lab with the same respect that you would treat any other position. See section on Hours.

## Small Picture

- Do not come into the lab if you are sick. Stay home and get healthy, and don't risk getting others sick.
- Notify the lab manager or me if you will be out, either due to illness or vacation. Make a note on the lab calendar when you have plans to be out. If you are sick and you had experiments or meetings scheduled that day, notify your participants or collaborators and reschedule. Please also update your Slack status.
- You are not expected to come into lab on ​staff holidays.​ If you are being paid, then you a​ re expected to come into lab during university breaks (except for staff holidays or if you're taking yourp​ aidvacationtime)​.
- Lock the doors to the lab if no one else is around, even if you're stepping out for a minute.
- Keep the lab tidy. Food messes should be cleaned up promptly, dirty dishes taken home with you,
and common areas should be kept free of clutter. Items left unattended may be cleaned,
reclaimed, or recycled. If you're using lab equipment, put it away when you're done.
- The dress code in academia is generally casual. My only request is that you look semi-professional when interacting with participants and when presenting your work. Jeans are fine, gym clothes and pajamas are not.
- Arrive to lab at least 15 minutes before you have any experiments scheduled, so that you will be there to greet the participants.

