# Rights and responsibilities {.unnumbered}

As a member of the iHuman Lab, you are entitled to certain rights, and you agree to take on certain responsibilities.

## Your rights as a lab member
1. You are entitled to a safe work environment free from harassment,
abuse, violence, and discrimination in any form.
2. You are entitled to be supported and respected by all lab members.
3. You are entitled to openly share your scientific ideas and constructive feedback with all lab members.
4. You are entitled to appropriate credit (e.g. authorship, acknowledgement, letter of recommendation) for your work and ideas.

## Your responsibilities as a lab member
1. You agree to contribute to a safe work environment and to refrain from behaviors that harass, abuse, expose to violence, or discriminate.
2. You agree to support and respect all lab members, including yourself.
3. You agree to openly share your scientific ideas and constructive feedback with other lab members.
4. You agree to clearly communicate and document your contributions to each research project (e.g. through `GitHub` commits and issues, reports, updates on `Slack`, etc.).
5. You agree to establish open lines of communication between yourself and other lab members, and to address concerns or issues promptly and directly with the relevant parties (to the extent that you feel safe doing so).
6. You agree to carry out your work with integrity and diligence, adhering to the highest possible standards of scientific excellence.
7. You agree to utilize lab resources (including equipment, money, time, etc.) responsibly and sustainably.
8. You agree to maintain a clean workspace free from clutter, including both personal spaces (e.g. desks) and shared areas (couch, sink, testing rooms, etc.).

:::{.callout-note title=Task}
Read this [letter](https://www.science.org/content/article/what-can-we-learn-dartmouth){target="_blank"} about defining and characterizing boundaries between lab members and noticing unhealthy norms.
:::

## Big Picture

- Do work that you are proud of. Do work that others will care about.
- Double-check your work. Being a little obsessive is essential to good science.
- Be supportive of your labmates. We are a team.
- Work independently when you can, ask for help when you need it.
- Share your knowledge. Mentorship can take many forms.
- Respect each others' strengths, weaknesses, differences, and beliefs.
- Science is a marathon, not a sprint. Take personal time/ vacation when you need it and cultivate a life outside of the lab. Respect that other lab members also have a life outside of lab.
- Communicate openly and respectfully with other members of the lab.
- If you have an issue with another lab member that cannot be solved by talking with them about it, please talk with Hemanth.
- Academia may feel different from other types of jobs, but it is still a job. You should treat coming into lab with the same respect that you would treat any other position.

## Small Picture

- Do not come into the lab if you are sick. Stay home and get healthy, and don't risk getting others sick.
- Notify the lab manager or me if you will be out, either due to illness or vacation. Make a note on the lab calendar when you have plans to be out. If you are sick and you had experiments or meetings scheduled that day, notify your participants or collaborators and reschedule. Please also update your `Slack` status.
- You are not expected to come into lab on ​staff holidays.​ If you are being paid, then you a​re expected to come into lab during university breaks (except for staff holidays or if you're taking your p​aid vacation time)​.
- Lock the doors to the lab if no one else is around, even if you're stepping out for a minute.
- Keep the lab tidy. Food messes should be cleaned up promptly, dirty dishes taken home with you,
and common areas should be kept free of clutter. Items left unattended may be cleaned,
reclaimed, or recycled. If you're using lab equipment, put it away when you're done.
- The dress code in academia is generally casual. My only request is that you look semi-professional when interacting with participants and when presenting your work. Jeans are fine, gym clothes and pajamas are not.
- Arrive to lab at least 15 minutes before you have any experiments scheduled, so that you will be there to greet the participants.


## Recourse
If you feel your rights as a lab member have been, or are in danger of being, violated, it is your duty to report those violations immediately to a senior staff member (e.g. Hemanth, Department Chair, Deans, police, Title IX coordinator, etc.). Similarly, if you notice others endangering others’ rights, or neglecting their responsibilities, it is your duty to report those violations to a senior staff member.

